# Lab 1.4: replication-factor 3 — overlay for helm/base-disk-cluster-values.yaml
aerospikeConfig:
  namespaces:
    - name: test
      replication-factor: 3
      migrate-sleep: 0 # For demo purposes only
      indexes-memory-budget: 46385646796  # 80% of 54 GiB (85% of 64 GiB) = 43.2 GiB
      storage-engine:
        type: device
        devices:
          - /dev/data/local1
