# Lab 1.4: replication-factor 3 — overlay for helm/base-dim-cluster-values.yaml
aerospikeConfig:
  namespaces:
    - name: test
      replication-factor: 3
      migrate-sleep: 0 # For demo purposes only
      indexes-memory-budget: 14495514624  # 25% of 54 GiB (85% of 64 GiB) = 13.5 GiB
      storage-engine:
        type: memory
        data-size: 28991029248  # 50% of 54 GiB (85% of 64 GiB) = 27 GiB
