#!/usr/bin/env python3
"""Generate the Section 4 all-flash CR manifests and Helm values.

EKS pairs 5 data devices with 1 index mount; GKE pairs 16 with 16. Hand-maintaining
32 volume stanzas per file is how they drift, so both Path A manifests and both
Path B value files are generated from the profiles below.

    ./scripts/labs/render-all-flash-manifests.py            # write all four files
    ./scripts/labs/render-all-flash-manifests.py --check    # fail if they are stale

Volume sizing must stay under what scripts/setup/nvme-bootstrap/disk-layouts.yaml provisions:
  EKS  i8ge.3xlarge-all-flash   5 × 1024 GiB data slices + 1 × 640 GiB ext4 index
  GKE  n2-highmem-16-all-flash  16 × ~335 GiB data slices + 16 × 40 GiB ext4 index
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

WORKSHOP_ROOT = Path(__file__).resolve().parents[2]

IMAGE_REPOSITORY = "aerospike/aerospike-server-enterprise"
IMAGE_TAG = "8.1.0.0"
EXPORTER_IMAGE = "aerospike/aerospike-prometheus-exporter:1.33.0"
CLUSTER_SIZE = 3
# 600 GiB of primary index per node, on both clouds.
MOUNTS_BUDGET = 644245094400
# 2^14. Raising this later needs a rolling cold restart — see instructor notes.
PARTITION_TREE_SPRIGS = 16384


class Profile:
    def __init__(
        self,
        key: str,
        cloud: str,
        node_type: str,
        cpu: str,
        memory: str,
        data_volumes: int,
        data_size: str,
        index_volumes: int,
        index_size: str,
        index_note: str,
    ) -> None:
        self.key = key
        self.cloud = cloud
        self.node_type = node_type
        self.cpu = cpu
        self.memory = memory
        self.data_volumes = data_volumes
        self.data_size = data_size
        self.index_volumes = index_volumes
        self.index_size = index_size
        self.index_note = index_note

    @property
    def data_paths(self) -> list[str]:
        return [f"/dev/data/local{i}" for i in range(1, self.data_volumes + 1)]

    @property
    def index_paths(self) -> list[str]:
        return [f"/mnt/index/{i}" for i in range(1, self.index_volumes + 1)]


PROFILES = {
    "eks": Profile(
        key="eks",
        cloud="AWS EKS",
        node_type="i8ge.3xlarge",
        cpu="10",
        memory="64Gi",
        data_volumes=5,
        data_size="1000Gi",
        index_volumes=1,
        index_size="600Gi",
        index_note="one 640 GiB ext4 slice on the single NVMe; 600 GiB claimed",
    ),
    "gke": Profile(
        key="gke",
        cloud="GCP GKE",
        node_type="n2-highmem-16",
        cpu="12",
        memory="64Gi",
        data_volumes=16,
        data_size="300Gi",
        index_volumes=16,
        index_size="38400Mi",
        index_note="one 40 GiB ext4 slice per disk; 37.5 GiB × 16 = 600 GiB claimed",
    ),
}


def header(profile: Profile, kind: str) -> str:
    return f"""# GENERATED by scripts/labs/render-all-flash-manifests.py — do not edit by hand.
#
# Section 4 all-flash {kind} for {profile.cloud} ({profile.node_type}).
# Primary index lives on local NVMe (index-type flash), not in DRAM:
#   data  {profile.data_volumes} × {profile.data_size} raw block volumes (local-ssd)
#   index {profile.index_volumes} × {profile.index_size} filesystem volumes (local-ssd-fs) — {profile.index_note}
#   mounts-budget {MOUNTS_BUDGET} bytes = 600 GiB of index per node
#
# Requires the all-flash cluster from setup step 0.8 (vm.dirty_* kernel settings
# and the paired index/data NVMe slices are not present on the main cluster).
"""


def volumes(profile: Profile, indent: str) -> str:
    """Shared storage.volumes list — identical in the CR and the Helm values."""
    out: list[str] = []

    def emit(line: str = "") -> None:
        out.append(f"{indent}{line}" if line else "")

    emit("- name: workdir")
    emit("  source:")
    emit("    persistentVolume:")
    emit("      storageClass: ssd")
    emit("      volumeMode: Filesystem")
    emit("      size: 3Gi")
    emit("  aerospike:")
    emit("    path: /opt/aerospike")

    for number, path in enumerate(profile.data_paths, start=1):
        emit(f"- name: ns-data-{number}")
        emit("  source:")
        emit("    persistentVolume:")
        emit("      storageClass: local-ssd")
        emit("      volumeMode: Block")
        emit('      accessModes: ["ReadWriteOnce"]')
        emit(f"      size: {profile.data_size}")
        emit("  aerospike:")
        emit(f"    path: {path}")

    for number, path in enumerate(profile.index_paths, start=1):
        emit(f"- name: ns-index-{number}")
        emit("  source:")
        emit("    persistentVolume:")
        emit("      storageClass: local-ssd-fs")
        emit("      volumeMode: Filesystem")
        emit('      accessModes: ["ReadWriteOnce"]')
        emit(f"      size: {profile.index_size}")
        emit("  aerospike:")
        emit(f"    path: {path}")

    emit("- name: aerospike-config-secret")
    emit("  source:")
    emit("    secret:")
    emit("      secretName: aerospike-secret")
    emit("  aerospike:")
    emit("    path: /etc/aerospike/secret")
    return "\n".join(out)


def namespace_config(profile: Profile, indent: str) -> str:
    out: list[str] = []

    def emit(line: str = "") -> None:
        out.append(f"{indent}{line}" if line else "")

    emit("- name: test")
    emit("  replication-factor: 2")
    emit("  migrate-sleep: 0 # For demo purposes only")
    emit(f"  partition-tree-sprigs: {PARTITION_TREE_SPRIGS}  # 2^14 — raising this needs a cold restart")
    emit("  # No indexes-memory-budget: the primary index is on flash, not in DRAM.")
    emit("  index-type:")
    emit("    type: flash")
    emit("    mounts:")
    for path in profile.index_paths:
        emit(f"      - {path}")
    emit(f"    mounts-budget: {MOUNTS_BUDGET}")
    emit("  storage-engine:")
    emit("    type: device")
    emit("    devices:")
    for path in profile.data_paths:
        emit(f"      - {path}")
    return "\n".join(out)


def access_control(indent: str) -> str:
    return "\n".join(
        f"{indent}{line}" if line else ""
        for line in """users:
  - name: admin
    secretName: auth-secret
    roles:
      - sys-admin
      - user-admin
  - name: app
    secretName: auth-app-secret
    roles:
      - read
      - write
  - name: exporter
    secretName: auth-exporter-secret
    roles: []""".split("\n")
    )


def exporter_sidecar(indent: str) -> str:
    return "\n".join(
        f"{indent}{line}" if line else ""
        for line in f"""- name: aerospike-prometheus-exporter
  image: {EXPORTER_IMAGE}
  ports:
    - containerPort: 9145
      name: exporter
  env:
    - name: AS_AUTH_USER
      value: exporter
    - name: AS_AUTH_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: auth-exporter-secret
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi""".split("\n")
    )


def render_manifest(profile: Profile) -> str:
    return f"""{header(profile, "AerospikeCluster")}apiVersion: asdb.aerospike.com/v1
kind: AerospikeCluster
metadata:
  name: aerocluster
  namespace: aerospike
spec:
  size: {CLUSTER_SIZE}  # TRAINEE EDIT in Lab 4.2 (3 -> 4)
  image: {IMAGE_REPOSITORY}:{IMAGE_TAG}
  enableDynamicConfigUpdate: true

  podSpec:
    nodeSelector:
      workshop.aerospike.com/node-pool: baseline
    multiPodPerHost: false
    aerospikeContainer:
      # Sized for the all-flash node, not for a DRAM index: {profile.node_type}.
      resources:
        requests:
          cpu: "{profile.cpu}"
          memory: {profile.memory}
        limits:
          cpu: "{profile.cpu}"
          memory: {profile.memory}
    sidecars:
{exporter_sidecar("      ")}

  storage:
    localStorageClasses:
      - local-ssd
      - local-ssd-fs
    filesystemVolumePolicy:
      cascadeDelete: true
      initMethod: deleteFiles
    blockVolumePolicy:
      cascadeDelete: true
      initMethod: blkdiscardWithHeaderCleanup
      wipeMethod: blkdiscard
    volumes:
{volumes(profile, "      ")}

  aerospikeAccessControl:
{access_control("    ")}

  aerospikeConfig:
    service:
      feature-key-file: /etc/aerospike/secret/features.conf
    security: {{}}
    network:
      service:
        port: 3000
      fabric:
        port: 3001
      heartbeat:
        port: 3002
      admin:
        port: 3003
    namespaces:
{namespace_config(profile, "      ")}
"""


def render_values(profile: Profile) -> str:
    return f"""{header(profile, "Helm values")}replicas: {CLUSTER_SIZE}
enableDynamicConfigUpdate: true

image:
  repository: {IMAGE_REPOSITORY}
  tag: "{IMAGE_TAG}"

podSpec:
  nodeSelector:
    workshop.aerospike.com/node-pool: baseline
  multiPodPerHost: false
  aerospikeContainer:
    # Sized for the all-flash node, not for a DRAM index: {profile.node_type}.
    resources:
      requests:
        cpu: "{profile.cpu}"
        memory: {profile.memory}
      limits:
        cpu: "{profile.cpu}"
        memory: {profile.memory}
  sidecars:
{exporter_sidecar("    ")}

storage:
  localStorageClasses:
    - local-ssd
    - local-ssd-fs
  filesystemVolumePolicy:
    cascadeDelete: true
    initMethod: deleteFiles
  blockVolumePolicy:
    cascadeDelete: true
    initMethod: blkdiscardWithHeaderCleanup
    wipeMethod: blkdiscard
  volumes:
{volumes(profile, "    ")}

aerospikeAccessControl:
{access_control("  ")}

aerospikeConfig:
  service:
    feature-key-file: /etc/aerospike/secret/features.conf
  security: {{}}
  network:
    service:
      port: 3000
    fabric:
      port: 3001
    heartbeat:
      port: 3002
    admin:
      port: 3003
  namespaces:
{namespace_config(profile, "    ")}
"""


def targets() -> dict[Path, str]:
    out: dict[Path, str] = {}
    for key, profile in PROFILES.items():
        suffix = "" if key == "eks" else f"-{key}"
        out[WORKSHOP_ROOT / "manifests" / f"all-flash-cluster{suffix}.yaml"] = render_manifest(profile)
        out[WORKSHOP_ROOT / "helm" / f"base-all-flash-cluster{suffix}-values.yaml"] = render_values(profile)
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when a generated file is missing or out of date",
    )
    args = parser.parse_args()

    stale: list[Path] = []
    for path, content in targets().items():
        if args.check:
            if not path.is_file() or path.read_text() != content:
                stale.append(path)
            continue
        path.write_text(content)
        print(f"wrote {path.relative_to(WORKSHOP_ROOT.parent)}")

    if stale:
        for path in stale:
            print(f"STALE {path.relative_to(WORKSHOP_ROOT.parent)}", file=sys.stderr)
        print("Run scripts/labs/render-all-flash-manifests.py to regenerate.", file=sys.stderr)
        return 1
    if args.check:
        print("all-flash manifests up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
